### ISSUE TITLE
Problem parsing the power.state Standby

### ISSUE THREAD

**Issue by ejones7** [bezmi/homeassistant_jvc_projector_remote#10]
First let me say thank you for time on this. I have been using it for a while and it allows me to integrate my JVC DLA-RS600U into Home Assistant. Also, thanks for restoring the extended attributes for last_command_sent, etc.

Please contact me if you have any questions on my description.

The issue began with your last update. It looks like the remote.py code is passing the power_state object (not the value) when in Standby mode. Here are the JSON errors:

Logger: homeassistant.components.websocket_api.messages
Source: components/websocket_api/messages.py:197
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: May 31, 2022, 11:26:15 PM (2 occurrences)
Last logged: May 31, 2022, 11:26:15 PM

Unable to serialize to JSON. Bad data found at $.event.c.remote.projector.+.a.power_state=PowerStates.standby(<enum 'PowerStates'>
Unable to serialize to JSON. Bad data found at $.event(Event: state_changed).data.new_state(State: remote.projector).attributes.power_state=PowerStates.standby(<enum 'PowerStates'>

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:315
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:26:34 AM (2 occurrences)
Last logged: 1:37:01 AM

[139859599606256] Unable to serialize to JSON. Bad data found at $.event.a.remote.projector.a.power_state=PowerStates.standby(<enum 'PowerStates'>
[139859610471584] Unable to serialize to JSON. Bad data found at $.event.a.remote.projector.a.power_state=PowerStates.standby(<enum 'PowerStates'>

**Comment by ejones7** [comment]
I believe the issue started with version 1.0.2 which rolled out at the end of May. Any backup before ~ May 20th should be okay.

**Comment by bezmi** [comment]
Sorry guys, I'll get this sorted ASAP. The enum stuff seems to be a relatively simple bug in the upstream python library. The "blocking call to sleep" error is possibly just because something is spamming the power_state() command (which is bugging out). There is an async version in the works, but hopefully fixing the main bug should fix the sleep issue also.

**Comment by bezmi** [comment]
Hi guys, I've rolled back a change in the python library and pushed a release. The manifest for this plugin should now point to the new release. Could someone please test it and let me know if it is working as expected?

**Comment by ziptbm** [comment]
> Hi guys, I've rolled back a change in the python library and pushed a release. The manifest for this plugin should now point to the new release. Could someone please test it and let me know if it is working as expected?

Success!  Just updated and it’s now showing lamp status and appears to reporting status correctly for me.  Will keep an eye on it and report back if anything changes.  Thank you!

**Comment by bezmi** [comment]
Thanks for the update. I'll have to investigate this sleep issue when time permits. Is it actually causing any noticeable stability issues for your homeassistant install?

**Comment by ziptbm** [comment]
> Thanks for the update. I'll have to investigate this sleep issue when time permits. Is it actually causing any noticeable stability issues for your homeassistant install?

Nothing I can tell.  I only see the error in logs when I “power off” the projector.

**Comment by bezmi** [comment]
@ziptbm I have released a version called `1.0.2 Testing` that may fix the "detected blocking call" issue. It should be visible in HACS. The current version that you're using is released as `1.0.2 Stable` (can also just use the default branch). If you have time, could you please install the testing version and let me know if the issue has been fixed?

**Comment by bezmi** [comment]
closing, as it is fixed in the latest alpha version #12. Please see the community post [here](https://community.home-assistant.io/t/jvc-projector-component/123417/38?u=bezmi).
