### ISSUE TITLE
no attribute 'validate_connection'

### ISSUE THREAD

**Issue by elmer2004** [bezmi/homeassistant_jvc_projector_remote#14]
Hello, I am trying to install JVCRemote on my HA and am getting the below error.

I have installed the latest beta version using HACS, restarted HA, and then modified my configuration.yaml, restarted again and am getting the error shown below.

I am fairly new to installing custom objects like this in HA, so my apologies if this is a simple and obvious user error and not a true issue.

Thanks for all of the work putting this together, I am really looking forward to getting it to work with my JVC RS-2100.

Logger: homeassistant.components.remote
Source: custom_components/jvcprojector/remote.py:75
Integration: Remote (documentation, issues)
First occurred: 10:06:46 PM (1 occurrences)
Last logged: 10:06:46 PM

Error while setting up jvcprojector platform for remote
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/jvcprojector/remote.py", line 39, in setup_platform
    JVCRemote(name, host, password, port, delay, timeout, retries),
  File "/config/custom_components/jvcprojector/remote.py", line 75, in __init__
    self._power_state = "not_connected" if not self._jvc.validate_connection() else self._jvc.power_state()
AttributeError: 'JVCProjector' object has no attribute 'validate_connection'

**Comment by bezmi** [comment]
Hi there, apologies for the issue. You should install version 2.0.0a2 (2.0.0 Alpha 2), which should work and is the verison that I'd expect everyone to install. 

The version you've installed is still in development and requires an updated python module. I'll have to look into why HACS is recommending that branch as the latest beta, apologies for that.

**Comment by elmer2004** [comment]
Thanks - I removed and re-installed it and it worked great, thank you!
