### ISSUE TITLE
HA keeps restarting in a loop

### ISSUE THREAD

**Issue by Letzdeal3** [bezmi/homeassistant_jvc_projector_remote#6]
Hi, had this working then all of a sudden home assistant keeps reconnecting. Only way to recover is to remove the remote configuration out of the config yaml. Not a huge HACS expert but dont see any issues in the logs. What file would you need to help resolve this if it possible.

Let me know as I would love to be able to turn off the projector during a power outage and running on UPS. Lens memory change would be useful as well.

Thanks
Derek

**Comment by bezmi** [comment]
Closing this one. Please reopen if this problem persists on the latest version.
